name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.3

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          path: github-repo  # Specify a folder to store the GitHub repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build the Docker image
        run: docker build ./github-repo --file github-repo/Dockerfile --tag namtranquoc/test-deployment:$VERSION

      - name: Push the Docker image
        run: docker push namtranquoc/test-deployment:$VERSION

      - name: Get image digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' namtranquoc/test-deployment:$VERSION)
          echo "DIGEST=${DIGEST}" >> $GITHUB_ENV

      - name: Clone the GitLab repository
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/wolfnam16/deployment.git gitlab-repo || exit 1
          cd gitlab-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          ls -l

      - name: Update `newTag` in `kustomization.yaml`
        run: |
          cd gitlab-repo/projects/dev/koffi/test
          sed -i "s/digest: .*/digest: $DIGEST # ${{ github.sha }}/" kustomization.yaml
          git add kustomization.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      - name: Clean up
        run: rm -rf gitlab-repo github-repo
