name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx (allows multi-platform builds)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as GitHub secret
        password: ${{ secrets.DOCKER_PASS }}  # Docker Hub password stored as GitHub secret

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag namtranquoc/test-deployment:${{ github.sha }}

    - name: Push the Docker image
      run: docker push namtranquoc/test-deployment:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Clone the GitLab repository
      run: |
        git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/wolfnam16/deployment.git
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        cd deployment
        ls -l

    - name: Update `newTag` in `kustomization.yaml`
      run: |
        ls -l
        cd deployment
        ls -l
        cd projects
        ls -l
        cd dev
        ls -l
        cd koffi
        ls -l
        cd test
        sed -i "s/newTag: .*/newTag: ${{ github.sha }}/" kustomization.yaml
        cd ../../../
        git add projects/dev/koffi/test/kustomization.yaml
        git commit -m "Update newTag to ${{ github.sha }}"
        git push

    - name: Clean up
      run: rm -rf deployment